### ISSUE TITLE
Deprecated functions, classes etc in ng-effects 9

### ISSUE THREAD

**Issue by st-clair-clarke** [stupidawesome/ng-effects#13]
Hi,
I am going through the series relating to ng-effects at [https://dev.to/stupidawesome/getting-started-with-angular-effects-2pdh](https://dev.to/stupidawesome/getting-started-with-angular-effects-2pdh)

However, many classes, functions are marked as deprecated, to be re-engineered in version 10. I updated to ng-effects@next and version 10 is installed. But now, going through the tutrorial, thee is no Effects provider.

Could you please recommend what is current?
Can ng-effects 9 be used in angular 10>
Is the library being maintained?

Thanks

**Comment by stupidawesome** [comment]
Hey there, thanks for the question. The version of the library used in that tutorial is no longer maintained. If you want to use it, I recommend forking the latest 9.0.x release. There are a number of reasons I abandoned the use of that particular pattern, and after quite a bit of mucking about with alternatives like Vue's reactivity system I've come to realize it was a mistake, as it ends up going in a completely different direction that is at odds with almost all other Angular-based projects. I'm currently waiting to see what the future brings before I resume this project.

**Comment by st-clair-clarke** [comment]
Thanks. Sorry to hear about the abandonment. I love the whole idea of reactivity in Angular..

**Comment by stupidawesome** [comment]
For those interested, I've published a spiritual successor this library: [Angular Composition API](https://github.com/mmuscat/angular-composition-api).
